# Example: Full-stack Node.js application with Postgres

version: '3.9'

services:
  # ============================================
  # Frontend - React/Next.js
  # ============================================
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: myapp-frontend
    restart: unless-stopped

    # Network configuration
    ports:
      - "3000:3000"
    networks:
      - frontend

    # Environment variables
    environment:
      REACT_APP_API_URL: http://localhost:8000
      NODE_ENV: production

    # Dependencies
    depends_on:
      api:
        condition: service_healthy

    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

    # Logging
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # ============================================
  # Backend API - Express/Fastify
  # ============================================
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: myapp-api
    restart: unless-stopped

    # Network configuration
    ports:
      - "8000:8000"
    networks:
      - frontend
      - backend

    # Environment variables
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      REDIS_URL: redis://cache:6379
      API_PORT: "8000"

    # Dependencies - wait for healthchecks
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy

    # Volumes for logs
    volumes:
      - ./logs:/app/logs

    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

    # Resource limits
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M

    # Logging
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # ============================================
  # PostgreSQL Database
  # ============================================
  db:
    image: postgres:16-alpine
    container_name: myapp-db
    restart: unless-stopped

    # Network configuration
    networks:
      - backend
    # Don't expose port to host in production
    ports:
      - "5432:5432"

    # Environment variables
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-myuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-mypassword}
      POSTGRES_DB: ${POSTGRES_DB:-mydb}

    # Volumes for persistent data
    volumes:
      - db_data:/var/lib/postgresql/data
      # Optional: Initialize database
      - ./init-db.sql:/docker-entrypoint-initdb.d/init.sql

    # Health check
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-myuser}"]
      interval: 10s
      timeout: 5s
      retries: 5

    # Resource limits
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M

    # Logging
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # ============================================
  # Redis Cache
  # ============================================
  cache:
    image: redis:7-alpine
    container_name: myapp-cache
    restart: unless-stopped

    # Network configuration
    networks:
      - backend
    ports:
      - "6379:6379"

    # Command with AOF persistence
    command: redis-server --appendonly yes

    # Volumes for persistence
    volumes:
      - cache_data:/data

    # Health check
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

    # Resource limits
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M

    # Logging
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # ============================================
  # Optional: pgAdmin for database management
  # ============================================
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: myapp-pgadmin
    restart: unless-stopped

    profiles:
      - dev  # Only in development: docker-compose --profile dev up

    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'

    networks:
      - backend

    ports:
      - "5050:80"

    depends_on:
      - db

    volumes:
      - pgadmin_data:/var/lib/pgadmin

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

# ============================================
# Named Volumes
# ============================================
volumes:
  db_data:
    driver: local
    driver_opts:
      type: tmpfs  # Optional: tmpfs for faster ops (data lost on restart)
      # type: local  # Standard filesystem

  cache_data:
    driver: local

  pgadmin_data:
    driver: local

# ============================================
# Networks
# ============================================
networks:
  # Frontend network - accessible from host
  frontend:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

  # Backend network - internal only
  backend:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16
